-- Create files table with blob storage
create table api.files (
  id int generated by default as identity primary key,
  blob bytea not null,
  type text not null,
  name text not null,
  created_at timestamptz not null default now()
);

-- Grant permissions
grant select on api.files to anon;
grant select, insert, delete on api.files to authenticated;

-- Function to upload file with base64 decoding
create or replace function api.upload_file(
  base64_data text,
  file_type text,
  file_name text
) returns api.files as $$
  insert into api.files (blob, type, name)
  values (decode(base64_data, 'base64'), file_type, file_name)
  returning *;
$$ language sql;

grant execute on function api.upload_file(text, text, text) to authenticated;

-- Create custom domain for binary responses
create domain "*/*" as bytea;

-- Function to serve files with proper headers
create or replace function api.file(file_id int) returns "*/*" as
$$
  declare headers text;
  declare blob bytea;
  begin
    select format(
      '[{"Content-Type": "%s"},'
       '{"Content-Disposition": "inline; filename=\"%s\""},'
       '{"Content-Length": "%s"},'
       '{"Cache-Control": "max-age=259200"}]'
      , files.type, files.name, length(files.blob))
    from api.files where files.id = file_id into headers;
    
    perform set_config('response.headers', headers, true);
    
    select files.blob from api.files where files.id = file_id into blob;
    
    if FOUND
    then return(blob);
    else raise sqlstate 'PT404' using
      message = 'NOT FOUND',
      detail = 'File not found',
      hint = format('%s seems to be an invalid file id', file_id);
    end if;
  end
$$ language plpgsql;

grant execute on function api.file(int) to anon, authenticated;
