create extension if not exists pgcrypto;
create extension if not exists pgjwt;

-- Migration tracking table
create table if not exists _migrations (
  id integer primary key,
  name text not null unique,
  applied_at timestamptz not null default now()
);

create schema api;

create table api.blog (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

insert into api.blog (title, body, published)
values
  ('first post', 'hello world', true),
  ('draft post', 'not published yet', false);

create table api.experience (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  description text,
  start_date date not null,
  end_date date,
  created_at timestamptz not null default now()
);

insert into api.experience (title, company, description, start_date, end_date)
values
  ('Software Engineer', 'Tech Corp', 'Developed web applications', '2023-01-01', '2024-12-31'),
  ('Junior Developer', 'StartupCo', 'Built REST APIs', '2021-06-01', '2022-12-31');

create table api.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text not null,
  role text not null default 'authenticated',
  created_at timestamptz not null default now()
);

-- Login function that returns JWT token
create or replace function api.login(email text, password text)
returns json as $$
declare
  _user api.users;
  _token text;
begin
  select * into _user
  from api.users
  where users.email = login.email
    and users.password = crypt(login.password, users.password);

  if _user.id is null then
    raise exception 'Invalid email or password';
  end if;

  return json_build_object(
    'token', sign(
      json_build_object(
        'role', _user.role,
        'user_id', _user.id,
        'email', _user.email,
        'exp', extract(epoch from now() + interval '8 hours')::bigint
      ),
      current_setting('app.jwt_secret')
    ),
    'user_id', _user.id,
    'email', _user.email,
    'role', _user.role
  );
end;
$$ language plpgsql security definer;

create role anon noinherit;
create role authenticated noinherit;

grant usage on schema api to anon, authenticated;

grant select on api.blog to anon;
grant select on api.experience to anon;

grant select, insert, update, delete on api.blog to authenticated;
grant select, insert, update, delete on api.experience to authenticated;

-- Grant execute permission on login function to anon
grant execute on function api.login(text, text) to anon;

-- Create authenticator role without password (password set by next init script)
create role authenticator noinherit login;
grant anon to authenticator;
grant authenticated to authenticator;
